# Agentic Researcher configuration
# Generated by: agentic-researcher --setup
#
# Location: ${XDG_CONFIG_HOME:-$HOME/.config}/agentic-researcher/config.sh
# Edit individual settings:  agentic-researcher --setup KEY=VALUE

# Container runtime: apptainer | docker | podman
AR_CONTAINER_RUNTIME="apptainer"

# Authentication: oauth | tool | api-key
# oauth: Claude Code handles login interactively
# tool:  the CLI handles auth inside the container; standard key env vars are passed through
# api-key: launcher validates AR_API_KEY_ENV before launch (mainly useful for Claude)
AR_AUTH_MODE="oauth"

# Optional provider metadata for advanced/custom setups
AR_API_PROVIDER="anthropic"

# Optional env var name for launcher-managed API key validation
AR_API_KEY_ENV="ANTHROPIC_API_KEY"

# For openai-compatible providers: base URL for OpenAI-compatible endpoint
AR_CUSTOM_ENDPOINT=""

# For openai-compatible providers: Anthropic SDK endpoint (used by Claude Code)
AR_CUSTOM_ANTHROPIC_ENDPOINT=""

# CLI tool: claude | opencode | gemini | codex
AR_CLI_TOOL="claude"

# Default model passed to the CLI tool (tool-specific)
AR_DEFAULT_MODEL="sonnet"

# HTTP(S) proxy (leave empty if not needed)
AR_HTTPS_PROXY=""
AR_HTTP_PROXY=""

# Base directory for local state, caches, and container temp data
AR_STATE_ROOT="$HOME/.cache/agentic-researcher"

# Additional directories to bind into the sandbox (colon-separated)
# Accepts commas or spaces too — they get normalized to colons
# Inside the container they appear under /workspace/.mount/<basename>
AR_EXTRA_BIND_DIRS=""
